
os: Visual Studio 2015

configuration:
    - Release

before_build:
    - md build
    - cd build

build_script:
    - cmake -TLLVM-vs2014 -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --config Release
    - ctest -C Release -j2 --output-on-failure
