# Based on https://docs.travis-ci.com/user/languages/c

language: c
sudo: false

branches:
  only:
    - master
    - branch_for_ci

matrix:
  include:

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - clang-3.9
      env:
        - BUILD_TYPE=RelWithDebInfo MATRIX_EVAL="CC=clang-3.9"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env:
        - BUILD_TYPE=RelWithDebInfo MATRIX_EVAL="CC=gcc-4.9"

    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - clang-3.9
      env:
        - BUILD_TYPE=Debug MATRIX_EVAL="CC=clang-3.9" CTEST_ARGS="-LE long"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env:
        - BUILD_TYPE=RelWithDebInfo MATRIX_EVAL="CC=gcc-5"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
        - COVERITY=1 BUILD_TYPE=RelWithDebInfo MATRIX_EVAL="CC=gcc-6" CMAKE_EXTRA_ARGS="-DCMAKE_C_FLAGS=-coverage"

    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
        - BUILD_TYPE=Debug MATRIX_EVAL="CC=gcc-6" CTEST_ARGS="-LE long"

    - os: osx
      osx_image: xcode8
      env:
        - BUILD_TYPE=Release MATRIX_EVAL=""

    - os: osx
      osx_image: xcode9
      env:
        - BUILD_TYPE=RelWithDebInfo MATRIX_EVAL=""

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE $CMAKE_EXTRA_ARGS .. || cat CMakeFiles/CMakeError.log
    - make VERBOSE=1 && ctest --output-on-failure -j2 $CTEST_ARGS

after_success:
    - if [[ $COVERITY -eq 1 ]]; then bash <(curl -s https://codecov.io/bash) ; fi
