
.SILENT: ;

tests:
	../util/runtests ../taltos *.in perftsuite/perft_002.in perftsuite/perft_106.in \
    perftsuite/perft_107.in perftsuite/perft_111.in perftsuite/perft_112.in \
    perftsuite/perft_113.in perftsuite/perft_114.in perftsuite/perft_074.in \
    perftsuite/perft_075.in perftsuite/perft_076.in perftsuite/perft_077.in \
    perftsuite/perft_082.in perftsuite/perft_083.in perftsuite/perft_064.in \
    perftsuite/perft_065.in perftsuite/perft_071.in perftsuite/perft_072.in \
    perftsuite/perft_066.in perftsuite/perft_067.in perftsuite/perft_069.in \
    perftsuite/perft_070.in

alltests:
	../util/runtests ../taltos *.in perftsuite/*.in

