# Copyright 2014-2017, Gabor Buella
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

generate_simple_tests()
{
	printf "# file generated by tools/gen_test_cmake.sh\n"
	printf "# do not edit manually\n"
	testdir=$1
	prefix=$2
	executable=$3
	for f in $testdir/*.in
	do
		echo
		test=${f%.in}
		printf "add_test(NAME \"%s%s\"\n" $prefix $(basename $test)
		printf "\tCOMMAND $<TARGET_FILE:%s> " $executable
		printf "\${PROJECT_SOURCE_DIR}/%s.in)\n" $test
	done
}

generate()
{
	printf "# file generated by tools/gen_test_cmake.sh\n"
	printf "# do not edit manually\n"
	testdir=$1
	prefix=$2
	for f in $testdir/*.in
	do
		echo
		test=${f%.in}
		printf "add_test(NAME \"%s%s\"\n" $prefix $(basename $test)
		printf "\tCOMMAND \${CMAKE_COMMAND}\n"
		printf "\t-DTEST_PROG=$<TARGET_FILE:taltos>\n"
		printf "\t-DCMP_PROG=$<TARGET_FILE:cmp_text>\n"
		printf "\t-DTEST_FILE=\${PROJECT_SOURCE_DIR}/%s\n" $test
		printf "\t-DNAME=%s\n" $(basename $test)
		printf "\t-P \${PROJECT_SOURCE_DIR}/cmake/expect.cmake)\n"
	done
}

generate tests/perftsuite > tests/perftsuite/CMakeLists.txt
generate tests/positions position_ > tests/positions/CMakeLists.txt
generate_simple_tests tests/perftsuite move_order_ test_move_order > \
	tests/perftsuite/CMakeLists_move_order.txt
generate_simple_tests tests/perftsuite eval_symmetry_ test_eval_symmetry > \
	tests/perftsuite/CMakeLists_eval_symmetry.txt
generate_simple_tests tests/perftsuite memcmp_ test_memcmp > \
	tests/perftsuite/CMakeLists_memcmp.txt
