
generate_simple_tests()
{
	printf "# file generated by tools/gen_test_cmake.sh\n"
	printf "# do not edit manually\n"
	testdir=$1
	prefix=$2
	executable=$3
	for f in $testdir/*.in
	do
		echo
		test=${f%.in}
		printf "add_test(NAME \"%s%s\"\n" $prefix $(basename $test)
		printf "\tCOMMAND $<TARGET_FILE:%s> " $executable
		printf "\${PROJECT_SOURCE_DIR}/%s.in)\n" $test
	done
}

generate()
{
	printf "# file generated by tools/gen_test_cmake.sh\n"
	printf "# do not edit manually\n"
	testdir=$1
	prefix=$2
	for f in $testdir/*.in
	do
		echo
		test=${f%.in}
		printf "add_test(NAME \"%s%s\"\n" $prefix $(basename $test)
		printf "\tCOMMAND \${CMAKE_COMMAND}\n"
		printf "\t-DTEST_PROG=$<TARGET_FILE:taltos>\n"
		printf "\t-DCMP_PROG=$<TARGET_FILE:cmp_text>\n"
		printf "\t-DTEST_FILE=\${PROJECT_SOURCE_DIR}/%s\n" $test
		printf "\t-DNAME=%s\n" $(basename $test)
		printf "\t-P \${PROJECT_SOURCE_DIR}/cmake/expect.cmake)\n"
	done
}

generate tests/perftsuite > tests/perftsuite/CMakeLists.txt
generate tests/positions position_ > tests/positions/CMakeLists.txt
generate_simple_tests tests/perftsuite move_order_ test_move_order > \
	tests/perftsuite/CMakeLists_move_order.txt
generate_simple_tests tests/perftsuite eval_symmetry_ test_eval_symmetry > \
	tests/perftsuite/CMakeLists_eval_symmetry.txt
generate_simple_tests tests/perftsuite memcmp_ test_memcmp > \
	tests/perftsuite/CMakeLists_memcmp.txt
